### ISSUE TITLE
matcher that doesnt require an object

### ISSUE THREAD

**Issue by mikecann** [paarthenon/variant#14]
I find myself doing something like this often:

```typescript
type BattleFinishedReason =
  | `PlayerAttack`
  | `PlayerTimeout`
  | `PlayerSurrender`
  | `PlayerCancelled`;

const   getReasonForBattleFinished = (): BattleFinishedReason  => { ... }

match(
    { type: getReasonForBattleFinished(battle) },
    {
    ...
    }
  );
```

It would be nice if there was a helper function that lets you just pass in a union to match on without the wrapping type so something like:

```typescript
matchOn(getReasonForBattleFinished(battle), {
...
});
```

Thoughts?

**Comment by paarthenon** [comment]
Try `matchLiteral`. I think it has the signature and function you're describing.

****
Still thinking about the other issue btw. Life's been busy.

****

I also do game dev with variant ;)

**Comment by mikecann** [comment]
> Try matchLiteral. I think it has the signature and function you're describing.

Oh awesome, probably being stupid but cant find the docs on that? https://paarthenon.github.io/variant/docs/api

> Still thinking about the other issue btw. Life's been busy.

Ye no worries :)

> I also do game dev with variant ;)

Awesome! Ye its a great lib, you have done a fantastic job.

**Comment by paarthenon** [comment]
Nah that's my mistake. Some quick history:

Originally `match`, `partialMatch`, `matchElse` and `matchLiteral` were all their own functions. Through overloads and conditional types I managed to get `match` to cover the functionality of both `partialMatch` and `matchElse` in version 2.0. `matchLiteral` is the only remaining item so I didn't talk about it hoping I could soon get it to *also* be covered by match. That said, this has resulted in some complexity with the match overload which makes it harder to do things like `matchKind` so I'm reconsidering that choice.

In the meantime I tell people about the hidden things in github issues because they are available and you are absolutely welcome to use them but they may be deprecated in the future. I try to hold myself to a higher standard for the stuff that's already been documented (and so may have people relying on it). 

Thank you! Please feel free to continue making any requests or suggestions like this. Not everything will fit here but I'm always open to good ideas.
