### ISSUE TITLE
Support for generic values

### ISSUE THREAD

**Issue by tomsdev** [paarthenon/variant#2]
Hi, thanks for the nice library and extensive documentation. I think one thing missing is when you'd want some variants to contain values with a generic type.

For example, imagine a Fetched<T> type which represents a request fetching some data of type T and can have 3 variants "fetching", "fetched" and "error". Here is some code snippets that doesn't work but just show the idea..:

```
const Fetched = variantList<Employee>([
  variant("fetching", fields<{ progress: number, previousData?: Employee }>()),
  variant("fetched", fields<{ data: Employee }>()),
  variant("error", fields<{ error: string }>()),
]);
type Fetched<T extends TypeNames<typeof Fetched> = undefined> = VariantOf<
  typeof Fetched,
  T
>;

```
By the way, I also tried a similar library which you might not know, it seems to require a bit less boilerplate than yours but there are probably other tradeoffs, but it also didn't support generic values: https://github.com/suchipi/safety-match

**Comment by paarthenon** [comment]
Hi,

Thanks for trying out the library. I agree, I've been working on achieving something like this but haven't struck home yet. 

****

I have not seen safety-match before. I played with it for a bit just now and took a look at the source. I don't think there's necessarily less boilerplate, I think the examples are smaller. As safety-match adds more features and matures it's probably going to have to look more like this project (though maybe not, our goals my differ). As you mention, there are tradeoffs. Please let me explain.

**Variant handles *any* valid discriminated union**. While I do prefer you use my tools because it's safer, you can write your own functions from scratch and variant's `match` will work with them just fine. It appears `safety-match` is very much scoped to the tagged union you create from `makeTaggedUnion`. That's a valid approach, but not the direction I wanted to go. It also seems that the type of `data` from my `const testObj = State.Loading(55)` is `any` which is not ideal. 

**Variant provides the union type**. The second line `type Animal<T extends ...` is not functionally necessary. I put that pattern in place in service to the consumer. By providing a type with the same name as the object when they `import {Animal} from '...';` they are actually importing the type as well (a kind of name punning). Having this union type available is very important as this is how you will describe the variant in any function that consumes it! `safety-match` wisely makes this available through their member type:

```typescript
import { MemberType } from "safety-match";
type StateType = MemberType<typeof State>;
```
I followed this pattern myself (search in my code history for the `OneOf<T>` type), but I found it very tedious to have to import this everywhere in practice. More often than not, the union is the type your users will want.

**It helps to have an easy to way to describe the generated object**. I provide this with `Animal<'snake'>`. I don't see an equivalent yet, though I may be missing it.

Boilerplate wise, it seems about the same to me ¯\\_(ツ)_/¯. This is [their usage example](https://github.com/suchipi/safety-match) in variant:

```typescript
const State = variantList([
    variant('Loading', (percentLoaded: number) => ({percentLoaded})),
    variant('Loaded', (response: Buffer) => response),
    variant('Unstarted'),
]);
type State<T extends TypeNames<typeof State> = undefined> = VariantOf<typeof State, T>;

let state = State.Unstarted();

const statusLine = match(state, {
    Unstarted: () => 'Waiting...',
    Loading: ({percentLoaded}) => `${percentLoaded} percent loaded`,
    Loaded: response => `Loaded ${response}`,
});

const percentComplete = match(state, {
    Unstarted: () => 0,
    Loading: ({percentLoaded}) => percentLoaded,
    Loaded: () => 100,
});

const isLoaded = partialMatch(state, {Loaded: () => true}) ?? false;
```
And if you really want you could delete the `type State<T extends TypeNames<typeof State> = undefined> = VariantOf<typeof State, T>;` and it wouldn't break anything, but it would make your type harder to use.

Fun fact that code doesn't actually work. With these types TypeScript actually has enough information to determine that the `Loading` and `Loaded` cases for `state` are not possible. If you copy/paste this into TS you'll need to change the line to `let state = State.Unstarted() as unknown as State;` to obfuscate the underlying type from the TS inference engine. 

### **This is in no way a criticism of @suchipi or [`suchipi/safety-match`](https://github.com/suchipi/safety-match)**. I like the direction they're going. I just think I'm further along that road at the moment. 

p.s. @suchipi I tagged you because I don't like the idea of passing commentary on someone's library without doing so. I hope you're doing well during the pandemic, and I hope you see this as fair—I'd be interested in your feedback as well. If you'd like to chat more on this or anything else I'm always available.

**Comment by tomsdev** [comment]
Thanks for the great explanation of the differences! You are right about the boilerplate, the main concern I have is with the optional type:
`type State<T extends TypeNames<typeof State> = undefined> = VariantOf<typeof State, T>;`

I understand why it's nice to have and that it can be generated by a VSCode snippet but I'm always a little worried that this would confuse a new developer that looks at my application code and tries to understand that line. I guess I'd add a comment on top to explain what it is.

I hope you will manage to add generic values support, I know it will be hard, these typescript types can get really complex..

**Comment by paarthenon** [comment]
Oh I hear you, I fiddled with this for a long time but this is the best alternative IMO. It may help to break down what exactly it is that's going on there.

`VariantOf<VariantDef, Type>` will generate the discriminated union. The second parameter `Type` will be evaluated as either

- A valid case of the variant (Animal)
    - which returns just the specific type `Animal<'snake'>`
- undefined
    - which returns `Animal<'dog'> | Animal<'cat'> | Animal<'snake'>`

This is optional, so if you want to you can just do this:

    type Animal = VariantOf<typeof Animal>

But then you can't get or pass the subtypes. So let's make our new type generic.

    type Animal<T> = VariantOf<typeof Animal, T>

Now we can do `Animal<'snake'>` and `Animal<undefined>` but I can't reference just `Animal` anymore, which I quite liked.

    type Animal<T = undefined> = VariantOf<typeof Animal, T>

So now I can do `Animal<'snake'>` and `Animal`. Great! But I can also do `Animal<'Rose'>` which... doesn't make sense. This will require us to restrict the type parameter of `Animal`. 

    type Animal<T extends TypeNames<typeof Animal> = undefined> = VariantOf<typeof Animal, T>;

Which is how we end up back here. You can pretty much stop at any point along this chain but you accept the caveats.

If you think that summary helps I'm happy to clean this up and put it into my readme so you could leave a link in a comment somewhere. 

I tend to have some notes on quirks for the libraries I'm using in my developers.md or lib.md file when working on a team project. Perhaps that would help?

**Comment by tomsdev** [comment]
Yes that helped a lot, I think you could definitely add that to some documentation!

In my case I think would sacrifice the autocompletion to keep the more readable type:
`type Animal<T = undefined> = VariantOf<typeof Animal, T>` 

But it's great to be able to choose!

**Comment by suchipi** [comment]
Thanks for tagging me; always good to see what similar libraries are doing.

fwiw @tomsdev, you can kinda fake generics in safety-match using function call type parameters, but it's not great: https://github.com/suchipi/safety-match/blob/40c6fd38601cc29aee3f614a38a2e9cc1a94fb9c/src/index.test.ts#L80

**Comment by suchipi** [comment]
Also, I didn't know you could use `const` and `type` with the same name to declare a binding that works as both a value and a type; that's pretty cool

**Comment by tomsdev** [comment]
@suchipi thanks for linking this example, however it's quite limited because with that approach you don't really have a generic value, the Maybe constructor will always contain a string value here so it should be named MaybeString.

**Comment by paarthenon** [comment]
> For example, imagine a Fetched type which represents a request fetching some data of type T and can have 3 variants "fetching", "fetched" and "error".

Hey Tom! How do you feel about this?

```typescript
const Fetched = <Employee>() => variantList([
    variant("fetching", fields<{ progress: number, previousData?: Employee }>()),
    variant("fetched", fields<{ data: Employee }>()),
    variant("error", fields<{ error: string }>()),
]);

type Employee = {
    id: number;
    name: string;
    accessLevel: number;
    startDate: Date;
};

const FetchedEmployee = Fetched<Employee>();
type FetchedEmployee<T extends TypeNames<typeof FetchedEmployee> = undefined> = VariantOf<typeof FetchedEmployee, T>;
```

**Comment by tomsdev** [comment]
I don't think this is enough, generics are used to combine types together without having to declare a new type for each combination possible, and to be able to write generic functions.

First it'd be quite annoying to have to declare every combinations possible. Every time I'd want to wrap a type inside a Fetched<>  (or a Maybe<>, or a Either<>, etc.) I would have to  write these 2 lines to declare that combination of types:
```
const FetchedEmployee = Fetched<Employee>();
type FetchedEmployee<T extends TypeNames<typeof FetchedEmployee> = undefined> = VariantOf<typeof FetchedEmployee, T>;
```

Now if I want to fetch Animal I have to again write these 2 lines:
```
const FetchedAnimal = Fetched<Animal>();
type FetchedAnimal<T extends TypeNames<typeof FetchedAnimal> = undefined> = VariantOf<typeof FetchedAnimal, T>;
```

But worse is that I can't write a generic function that takes any Fetched<T> object and show the current fetching status:

```
function showFetchStatus<T>(fetched: Fetched<T>) {
  match(fetched, {
    fetching: ({ progress }) => `fetching: ${progress}%`,
    fetched: () => "fetched",
    error: ({ error }) => `fetch error: ${error}`,
  });
}

showFetchStatus(FetchedEmployee.fetching({ progress: 50 }));
showFetchStatus(FetchedAnimal.fetching({ progress: 10 }));
```

A workaround would be to use the union of all possible Fetched<T> combinations as input:
```
function showFetchStatus(fetched: FetchedEmployee | FetchedAnimal) {
  match(fetched, {
    fetching: ({ progress }) => `fetching: ${progress}%`,
    fetched: () => "fetched",
    error: ({ error }) => `fetch error: ${error}`,
  });
}

```
But I don't think that'd be very practical..

**Comment by paarthenon** [comment]
Hi Tom @tomsdev !

So it took a little fiddling but I got it. Here is a *working* test in `variant 2.0.0-beta.2`. There's a branch `2.0` with a new function called `typedVariant`.

```typescript
test('issue #2', () => {
    type Fetched<T> =
        | Variant<'fetching', {progress: number, previousData?: T}>
        | Variant<'fetched', {data: T}>
        | Variant<'error', {error: string}>
    ;

    function showFetchedStatus<T>(fetched: Fetched<T>) {
        return match(fetched, {
            fetching: ({progress}) => `fetching ${progress}%`,
            fetched: () => 'fetched',
            error: ({error}) => `fetch error ${error}`,
        })
    }

    const getFetched = <T>() => typedVariant<Fetched<T>>({
        fetching: pass,
        fetched: pass,
        error: pass,
    });

    const FetchedAnimal = getFetched<Animal>();
    const FetchedEmployee = getFetched<Employee>();

    expect(showFetchedStatus(FetchedEmployee.fetching({progress: 50}))).toBe('fetching 50%');
    expect(showFetchedStatus(FetchedAnimal.fetching({progress: 10}))).toBe('fetching 10%');
})
```

As you can see, the `showFetchedStatus` function can be written before there are any concrete manifestations of `Fetched<T>`. In this example, `pass` is a helper function to communicate "simply receive the fields of my variant case and pass them on". If you wished to, you could instead write `fetched: ({data}) => ({data}),` or `fetched: x => x`. The point being, this is another area where you can add defaults, logging, etc. when desired and can simply use `pass` the rest of the time.

Does that achieve what you're looking for?

****

p.s. I'll also be adding a new way to create variants: `variantModule`

```typescript
export const Animal2 = variantModule({
    dog: fields<{name: string, favoriteBall?: string}>(),
    cat: fields<{name: string, daysSinceDamage: number}>(),
    snake: (name: string, pattern = 'striped') => ({name, pattern}),
    bird: nil,
});
export type Animal2<T extends TypeNames<typeof Animal2> = undefined> = VariantOf<typeof Animal2, T>;
```

I think this is rather cleaner. `nil` is used as a standin for what used to be `variant('bird')`. You may also use the value undefined.

****

I'm still developing and adding tests, but if you'd like to try out these changes yourself you can

     npm i variant@beta

**Comment by paarthenon** [comment]
Hello again @tomsdev  It's been a couple of weeks and variant 2.0.1 including the fix for this issue has been merged in. I'm going to be closing this for now. Thank you for bringing this up! Please feel free to reopen this issue or a new one if this approach doesn't address your needs.

**Comment by paarthenon** [comment]
Quoted from the other issue
> 
> I haven't updated the docs for this, so I wanted to post here in case it's relevant to you. These changes are available in `2.0.2-beta.6`
> 
> I added some better handling for recursive generics:
> 
> ```ts
> type Tree<T> =
>     | Variant<'Branch', {left: Tree<T>, right: Tree<T>}>
>     | Variant<'Leaf', {payload: T}>
> ;
> 
> const Tree = genericVariant(({A}) => ({
>     Branch: fields<{left: Tree<typeof A>, right: Tree<typeof A>}>(),
>     Leaf: payload(A),
> }));
> 
> const leaf = Tree.Leaf(4); // no need for separate numTree and animalTree constructors.
> ```
> 
> Attempting to use disparate types raises an error, as expected.
> 
> ![image](https://user-images.githubusercontent.com/10353928/98486880-e782b200-21ed-11eb-8ea4-4c3deebbc84d.png)
> If, however, the tree was created with `left` and `right` branches set to the generic terms `A` and `B` respectively, this no longer raises an error.
> 
> p.s. the `Variant<string, {}?>` type is very simply a stand-in for `{type: string} & {}?`. I encourage it for ergonomics, and because it's a possible entry point for future 'magic' for me, but it's not necessary.

**Comment by tomsdev** [comment]
> Note you no longer need separate implemented variants for Animal and Employee.

Wow, congrats on achieving this @paarthenon! I've looked at the documentatio you wrote too, looking great!

**Comment by paarthenon** [comment]
Thanks @tomsdev!

I've actually been working on further enhancements to this system. When trying this in the wild I found that actually constructing the wrapping result types was troublesome. There were some bugs with primitive types being interpreted as objects and the generic types weren't as usable as the regular types. I worked to improve that and think the results are encouraging.

You can see and experiment with a live sample of it at this stackblitz page:

https://stackblitz.com/edit/react-ts-dcmrug?file=option.ts

Please ignore the react component, it was just part of the template setup.
