### ISSUE TITLE
Casting between Union Types

### ISSUE THREAD

**Issue by danielwinkler** [paarthenon/variant#6]
Given the examples from the documentation on [Subsets and Combinations](http://paarth.io/variant/docs/use/grouping#subsets) I have two questions;

1. Is it possible to narrow union types?
```javascript
export const AnimalWithWings = variantList([
    Animal.bird,
    Animal.pegasus,
]);
export type AnimalWithWings<T extends TypeNames<typeof AnimalWithWings> = undefined> = VariantOf<typeof AnimalWithWings, T>;
export const AnimalWithFourLegs = variantList([
    Animal.cat,
    Animal.dog,
    Animal.pegasus,
]);
export type AnimalWithFourLegs<T extends TypeNames<typeof AnimalWithFourLegs> = undefined> = VariantOf<typeof AnimalWithFourLegs, T>;

const flap = (animal: AnimalWithWings) => {...} 
const a : Animal = someFunc();

// how can I check that a belongs to AnimalWithWings
```

2. Is it possible to define a type union based on a contract?
```javascript
// instead of explicitly listing all animals
// use the properties and define a contract
export type AnimalWithWings<T extends TypeNames<typeof A>, A extends Animal & {wingCount: number} > ...
```

I know this type makes no sense, but the idea is to define the type as union all Animal variants that have a wingCount property.

**Comment by paarthenon** [comment]
Hi there!

###  1. Is it possible to narrow union types?

Yes, you want [`isOfVariant`](http://paarth.io/variant/docs/api/#isofvariant)

> isOfVariant
> 
> Checks if an object was created from one of a set of variants. This function is a user-defined type guard so TypeScript will narrow the type of object correctly.
> 
>     object: {} | null | undefined an object.
>     variantModule: VariantModule the module to compare to. This can be a previously constructed object or stitched together on the fly through literals or variantList
>     typeKey?: K: The key used as the discriminant.

> returns object is variantModule

```typescript
declare var animal: {};

if (isOfVariant(animal, Animal)) {
    ... // animal is now of type Animal
}

if (isOfVariant(animal, variantList([Animal.cat, Animal.dog]))) {
    ... // animal is now of type Animal<'cat'> | Animal<'dog'>
}
```

### 2. Is it possible to define a type union based on a contract?

Yep. It's actually easier than you might think. Use [`Extract<T, U>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#extracttype-union).

> type AnimalWithWings = Extract<Animal, {wingCount: number}>;

****

Hope that helps! It's cool to see a link to the in-progress documentation. I'm still expanding a lot of it. How has it been for you so far? Hopefully it's a clear read?

**Comment by danielwinkler** [comment]
The documentation is very nice. I am really looking forward to refactor my code with  your variant package 💪 

Thanks for your quick reply!

**Comment by paarthenon** [comment]
I could certainly point you to some things. What part of it is understandable, and what part feels like magic?

For what it's worth, I _did not know how to build this project when I set out to build this project_. It all started with me wondering 

 1 "Hm... I'm tired of duplicating a string in the value space (object init) and type space (interface definition). 
 2. I wonder if I can tie the two together, or base one off of the other. I can't make a value based on a type, but I can make a type based on a value.
3. But I won't really have default values for a lot of these cases. What if I instead use the return value of a *function*? That way people could do whatever sort of optional parameters, default handling, etc. they want and I still get to interpret the types correctly. That sounds neat.
4. Hey while I'm at it it seems dumb that I have to manually make the `{type: "variantName"}` property for every constructor function. Can't I just make the constructor function patch in the type for me?

That took me a long afternoon of fucking around to put together. The rest of the project extended naturally from there.

1. I needed a way to express a "collection" of variants (resulted in `variantList`)
2. I need helper functions so that I can process them in a pretty way. (`match`, `lookup`, `isOfVariant`, etc.)
3. It would be nice to have helper functions for common creation patterns (`payload` and `fields`).

Repeat this process for a few weeks and ta-da, you've got variant!

Hope that helps.

**Comment by paarthenon** [comment]
ALSO, here, take a look at the code. **_Ignore the types completely for now._**

https://github.com/paarthenon/variant/blob/master/src/variant.ts#L51

The types are the hard part. The types are convincing TypeScript of what you already know to be true. 

But here is literally everything the `variant` function does:

1. Runs the function it got passed.
2. Adds a "type" property to the result.
3. Adds some metadata to the function so other library functions can interact with it. 

It's deceptively simple.

**Comment by danielwinkler** [comment]
Thanks a lot for your feedback!

I think i need to properly wrap my head around conditional types, especially in combination with `never`.
Maybe reading the advanced type part of the TS handbook in combination with the types in your repo will be a good starting point.

Thanks again for the nice work and your detailed feedback!

**Comment by danielwinkler** [comment]
@paarthenon I am now refactoring my code, your lib is sooo nice! congrats!

**Comment by paarthenon** [comment]
@danielwinkler That's so kind of you, thank you! I'm glad it's working for you. Watch this space, I'm working on Variant 2.0 which will feature generic and recursive variants and a new even simpler syntax to construct them.

```typescript
export const Animal2 = variantModule({
    dog: fields<{name: string, favoriteBall?: string}>(),
    cat: fields<{name: string, daysSinceDamage: number}>(),
    snake: (name: string, pattern = 'striped') => ({name, pattern}),
    bird: nil,
});
export type Animal2<T extends TypeNames<typeof Animal2> = undefined> = VariantOf<typeof Animal2, T>;
```
`nil` is used as a standin for what used to be `variant('bird')`. You can also just use the value undefined.
